Repository sjacorg/bayanat, pull requests merged in 2025-08, with the labels that each got.

#142 Show delete button as soon as ID Number input is dirty
  enferno/static/js/components/IdNumberDynamicField.js
Labels: project c

#146 Media file is not fully visible after rotation
  enferno/static/js/components/ImageViewer.js
Labels: project t

#126 bynt-1364: implement username and email validation for user endpoints
  enferno/admin/templates/admin/jsapi.jinja2
  enferno/admin/templates/admin/users.html
  enferno/admin/validation/models.py
  enferno/admin/views.py
  enferno/static/js/common/config.js
  enferno/user/forms.py
  enferno/utils/validation_utils.py
  tests/admin/test_users.py
  tests/user/test_webauthn_forms.py
  tests/validations/test_user_validation.py
  tests/validations/test_validation_models.py
Labels: project c

#153 Fix Code Scanning Potential Stack Trace exposure
  enferno/admin/views.py
  enferno/user/models.py
Labels: project t

#148 Truncate long descriptions and add "Show More" toggle
  enferno/admin/templates/admin/activity.html
  enferno/admin/templates/admin/actors.html
  enferno/admin/templates/admin/bulletins.html
  enferno/admin/templates/admin/eventtypes.html
  enferno/admin/templates/admin/incidents.html
  enferno/admin/templates/admin/jsapi.jinja2
  enferno/admin/templates/admin/labels.html
  enferno/admin/templates/admin/locations.html
  enferno/admin/templates/admin/partials/bulletin_dialog.html
  enferno/admin/templates/admin/sources.html
  enferno/data_import/templates/import-log.html
  enferno/deduplication/templates/deduplication.html
  enferno/export/templates/export-dashboard.html
  enferno/static/css/app.css
  enferno/static/js/components/ActorCard.js
  enferno/static/js/components/ActorProfiles.js
  enferno/static/js/components/BulletinCard.js
  enferno/static/js/components/IncidentCard.js
  enferno/static/js/components/LocationCard.js
  enferno/static/js/components/ReadMore.js
  enferno/static/js/components/RelateItemsTemplate.js
  enferno/static/js/components/RelatedActorsCard.js
  enferno/static/js/components/RelatedBulletinsCard.js
  enferno/static/js/components/RelatedIncidentsCard.js
Labels: project c

#159 Limit event comments to 255 chars
  enferno/static/js/components/EventsSection.js
Labels: project t

#158 Search for related a/b/i not using cursors
  enferno/admin/templates/admin/actors.html
  enferno/admin/templates/admin/bulletins.html
  enferno/admin/templates/admin/incidents.html
  enferno/admin/validation/models.py
  enferno/static/js/components/ExportCard.js
  enferno/static/js/components/RelateActors.js
  enferno/static/js/components/RelateBulletins.js
  enferno/static/js/components/RelateIncidents.js
  enferno/static/js/mixins/related-search-mixin.js
Labels: project t

#151 Inconsistency between the date entry format and the display format
  enferno/admin/templates/admin/activity.html
  enferno/admin/templates/admin/bulletins.html
  enferno/admin/templates/admin/system-administration.html
  enferno/admin/templates/admin/system-logs.html
  enferno/data_import/templates/import-log.html
  enferno/export/templates/export-dashboard.html
  enferno/static/js/common/config.js
  enferno/static/js/components/ActorCard.js
  enferno/static/js/components/ActorProfiles.js
  enferno/static/js/components/BulletinCard.js
  enferno/static/js/components/EventCard.js
  enferno/static/js/components/ExportCard.js
  enferno/static/js/components/ImportLogCard.js
  enferno/static/js/components/IncidentCard.js
  enferno/static/js/components/LocationCard.js
  enferno/static/js/components/PopDateField.js
  enferno/static/js/components/PopDateRangeField.js
  enferno/static/js/components/UserCard.js
  enferno/static/js/dayjs-with-plugins.min.js
  enferno/static/js/dayjs.min.js
  enferno/static/js/mixins/global-mixin.js
  enferno/templates/layout.html
Labels: project t

#163 UV
  .github/workflows/pip-audit.yml
  docker-compose.yml
  flask/Dockerfile
  flask/Dockerfile.test
  pyproject.toml
  requirements/dev.txt
  requirements/main.txt
  requirements/opt.txt
  uv.lock
Labels: project i

#157 Dialogs are fullscreen and not sizing properly
  enferno/admin/templates/admin/actors.html
  enferno/admin/templates/admin/bulletins.html
  enferno/admin/templates/admin/incidents.html
  enferno/admin/templates/admin/partials/actor_dialog.html
  enferno/admin/templates/admin/partials/bulletin_dialog.html
  enferno/admin/templates/admin/partials/incident_dialog.html
  enferno/static/css/app.css
  enferno/static/js/components/EventsSection.js
  enferno/static/js/components/GeoLocations.js
  enferno/static/js/components/ShortActorDialog.js
  enferno/static/js/components/SplitView.js
Labels: project t

#162 Improve test infrastructure and security updates
  .github/workflows/run-tests.yml
  config.test.json
  docker-compose-test.yml
  enferno/admin/models/Activity.py
  enferno/admin/models/Notification.py
  enferno/admin/validation/models.py
  enferno/app.py
  enferno/data_import/utils/media_import.py
  enferno/deduplication/views.py
  enferno/export/models.py
  enferno/extensions.py
  enferno/settings.py
  enferno/tasks/__init__.py
  enferno/user/models.py
  enferno/user/views.py
  enferno/utils/backup_utils.py
  enferno/utils/config_utils.py
  enferno/utils/db_alignment_helpers.py
  enferno/utils/validation_utils.py
  flask/Dockerfile.test
  tests/admin/test_actors.py
  tests/admin/test_bulletins.py
  tests/admin/test_incidents.py
  tests/admin/test_users.py
  tests/admin/test_whisper_endpoints.py
  tests/conftest.py
  tests/factories.py
  tests/public/test_rate_limiting.py
Labels: project i

#160 Broken progress steps in sheets import
  enferno/data_import/templates/sheets-import.html
Labels: project t

#167 Update uwsgi.ini for UV virtual environment
  uwsgi.ini
Labels: project c

#171 Fix Black invalid Configuration
  pyproject.toml
Labels: project t
