Repository sjacorg/bayanat, pull requests merged in 2025-09, with the labels that each got.

#177 Fix table not rendering on system logs page
  enferno/admin/templates/admin/system-logs.html
Labels: project t

#181 Fixes session handling issues with Flask-Session Redis backend during login/logout operations
  enferno/user/views.py
Labels: project t

#188 Session Dialog Fix - Implementation
  enferno/admin/views.py
  enferno/static/js/mixins/reauth-mixin.js
Labels: project i

#175 Add event date to popup in map
  enferno/admin/templates/admin/jsapi.jinja2
  enferno/static/js/common/config.js
  enferno/static/js/components/EventCard.js
  enferno/static/js/components/GlobalMap.js
  enferno/static/js/components/IncidentCard.js
  enferno/static/js/mixins/global-mixin.js
Labels: project m

#184 Related Items View Not Loading Correctly
  enferno/admin/templates/admin/actors.html
  enferno/admin/templates/admin/bulletins.html
  enferno/admin/templates/admin/incidents.html
Labels: project t

#183 Event locations list drop down after selection
  enferno/static/js/components/SearchField.js
Labels: project t

#193 Add scroll to menu in system administration page
  enferno/admin/templates/admin/system-administration.html
Labels: project i
